
vector<string> Color{

    "Red ",
    "Green",
    "Blue",
    "cyan",
    "peru ",
    "CadetBlue",
    "chartreuse",
    "CornflowerBlue",
    "DarkGoldenrod",
    "brown",
    "Gold",
    "DarkOrange ",
    "DarkViolet ",
    "DeepPink ",
    "DeepSkyBlue ",
    "Firebrick ",
    "HotPink ",
    "LawnGreen ",
    "LightCoral ",
    "LightSalmon ",
    "LightSeaGreen ",
    "LimeGreen ",
    "Magenta ",
    "Maroon ",
    "MediumAquamarine ",
    "MediumBlue ",
    "Orange ",
    "OrangeRed ",
    "Orchid ",
    "PaleGreen ",
    "PaleVioletRed ",
    "purple ",
    "RoyalBlue ",
    "SeaGreen ",
    "YellowGreen ",
    "salmon ",
    "RosyBrown ",
    "PaleTurquoise ",
    "ForestGreen ",
    "LightSkyBlue ",
    "LightPink ",
    "DarkTurquoise",
};
