-- MySQL Script generated by MySQL Workbench
-- Tue Jan 26 17:10:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema codeplag
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codeplag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codeplag` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `codeplag` ;

-- -----------------------------------------------------
-- Table `codeplag`.`ComparisonHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeplag`.`ComparisonHistory` ;

CREATE TABLE IF NOT EXISTS `codeplag`.`ComparisonHistory` (
  `compid` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `folderName` VARCHAR(250) NULL DEFAULT NULL,
  `fileCount` INT NULL DEFAULT NULL,
  `MatchedDataJson` MEDIUMTEXT NULL DEFAULT NULL,
  `fileDataJson` MEDIUMTEXT NULL DEFAULT NULL,
  `ComparisonDate` VARCHAR(70) NULL DEFAULT NULL,
  `language` VARCHAR(50) NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT 'pending',
  `comparisonTime` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`compid`),
  UNIQUE INDEX `unique_composite_key` (`email` ASC, `folderName` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 88
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `codeplag`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codeplag`.`users` ;

CREATE TABLE IF NOT EXISTS `codeplag`.`users` (
  `userid` VARCHAR(250) NOT NULL,
  `fullname` VARCHAR(250) NULL DEFAULT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `password` VARCHAR(250) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `activeToken` VARCHAR(250) NULL DEFAULT NULL,
  `activeExpires` VARCHAR(250) NULL DEFAULT NULL,
  `activestatus` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
