

vector <string> Color
{

    "Red ",
    "Green",
    "Blue",
    "cyan",
    "peru ",
    "CadetBlue",
    "chartreuse",
    "CornflowerBlue",
    "DarkGoldenrod",
    "brown",
    "Gold",
    "DarkOrange ",
    "DarkViolet ",
    "DeepPink ",
    "DeepSkyBlue ",
    "Firebrick ",
    "HotPink ",
    "LawnGreen ",
    "LightCoral ",
    "LightSalmon ",
    "LightSeaGreen ",
    "LimeGreen ",
    "Magenta ",
    "Maroon ",
    "MediumAquamarine ",
    "MediumBlue ",
    "Orange ",
    "OrangeRed ",
    "Orchid ",
    "PaleGreen ",
    "PaleVioletRed ",
    "purple ",
    "RoyalBlue ",
    "SeaGreen ",
    "YellowGreen ",
    "salmon ",
    "RosyBrown ",
    "PaleTurquoise ",
    "ForestGreen ",
    "LightSkyBlue ",
    "LightPink ",
    "DarkTurquoise",

    /* "<div style=\"color:red;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:blue;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:green;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Lime;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Cyan;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Purple;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Magenta;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Orange;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Maroon;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Olive;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Gold;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Coral;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:DarkSeaGreen;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:DarkTurquoise;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:FireBrick;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:DodgerBlue;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:GoldenRod;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:GreenYellow;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:IndianRed;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Indigo;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:HotPink;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:LightGreen;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:LightSalmon;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:LightSkyBlue;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Lime;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:MediumVioletRed;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:MediumSeaGreen;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Navy;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Orchid;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Peru;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:SpringGreen;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:SteelBlue;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Thistle;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Tomato;font-weight: bold;font-size:13px\">  ",
     "<div style=\"color:Aquamarine;font-weight: bold;font-size:13px\">  ",*/




    /*"<div style=\"color:AliceBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:AntiqueWhite;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:AntiqueWhite1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:AntiqueWhite2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:AntiqueWhite3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:AntiqueWhite4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:aquamarine1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:aquamarine2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:aquamarine3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:azure;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:azure2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:azure3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:azure4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:beige;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:bisque;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:bisque2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:bisque3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:bisque4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Black;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:BlanchedAlmond;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:blue1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:blue2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:blue3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:blue4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:BlueViolet;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:brown2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:brown3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:burlywood1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:burlywood2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:burlywood3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:burlywood4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:CadetBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:CadetBlue1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:CadetBlue2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:CadetBlue4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:chartreuse;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:chartreuse2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:chartreuse4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:chocolate;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Coral;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:coral2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:coral3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:coral4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:cornsilk;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:cornsilk2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:cornsilk3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:cornsilk4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Cyan;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:cyan1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:cyan2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:cyan3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:cyan4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkGoldenrod;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkGoldenrod1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkGoldenrod2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkGoldenrod3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkGoldenrod4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkKhaki;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOliveGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOliveGreen1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOliveGreen2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOliveGreen3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOliveGreen4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOrange;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOrange1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOrange2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOrange3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOrange4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOrchid;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOrchid1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOrchid2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOrchid3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkOrchid4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkSalmon;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkSeaGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkSeaGreen1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkSeaGreen2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkSeaGreen3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkSeaGreen4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkSlateBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkSlateGray;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkSlateGray1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkSlateGray2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkSlateGray3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkSlateGray4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkTurquoise;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DarkViolet;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DeepPink;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DeepPink2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DeepPink3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DeepPink4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DeepSkyBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DeepSkyBlue2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DeepSkyBlue3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DeepSkyBlue4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DimGray;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DodgerBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DodgerBlue2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DodgerBlue3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:DodgerBlue4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Firebrick;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:firebrick1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:firebrick2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:firebrick3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:FloralWhite;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:ForestGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:gainsboro;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:GhostWhite;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Gold;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:gold1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:gold2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:gold3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:gold4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Goldenrod;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:goldenrod1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:goldenrod2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:goldenrod3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:goldenrod4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Green;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:green1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:green2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:green3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:green4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:GreenYellow;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:honeydew;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:honeydew2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:honeydew3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:honeydew4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:HotPink;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:HotPink1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:HotPink2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:HotPink3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:HotPink4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:IndianRed;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:IndianRed1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:IndianRed2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:IndianRed3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:IndianRed4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:ivory;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:ivory2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:ivory3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:ivory4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Khaki;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:khaki1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:khaki2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:khaki3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:khaki4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:lavender;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LavenderBlush;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LavenderBlush2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LavenderBlush3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LavenderBlush4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LawnGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LemonChiffon;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LemonChiffon2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LemonChiffon3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LemonChiffon4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightBlue1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightBlue2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightBlue3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightBlue4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightCoral;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightCyan;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightCyan2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightCyan3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightCyan4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightGoldenrod;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightGoldenrod1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightGoldenrod2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightGoldenrod3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightGoldenrod4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightGoldenrodYellow;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightPink;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightPink1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightPink2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightPink3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightPink4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSalmon;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSalmon2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSalmon3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSalmon4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSeaGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSkyBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSkyBlue2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSkyBlue3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSkyBlue4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSlateBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSlateGray;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSteelBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSteelBlue1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSteelBlue2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSteelBlue3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightSteelBlue4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightYellow;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightYellow2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightYellow3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LightYellow4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:LimeGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:linen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Magenta;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:magenta1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:magenta2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:magenta3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Maroon;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:maroon1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:maroon2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:maroon3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:maroon4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumAquamarine;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumForestGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumGoldenrod;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumOrchid;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumOrchid1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumOrchid2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumOrchid3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumOrchid4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumPurple;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumPurple1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumPurple2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumPurple3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumPurple4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumSeaGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumSlateBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumSpringGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumTurquoise;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MediumVioletRed;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MidnightBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MintCream;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MistyRose;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MistyRose2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MistyRose3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:MistyRose4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:moccasin;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:NavajoWhite;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:NavajoWhite2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:NavajoWhite3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:NavajoWhite4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Navy;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:OldLace;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:OliveDrab;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:OliveDrab1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:OliveDrab2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:OliveDrab3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:OliveDrab4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Orange;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:orange1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:orange2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:orange3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:orange4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:OrangeRed;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:OrangeRed2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:OrangeRed3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:OrangeRed4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Orchid;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:orchid1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:orchid2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:orchid3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:orchid4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleGoldenrod;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleGreen1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleGreen2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleGreen3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleGreen4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleTurquoise;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleTurquoise1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleTurquoise2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleTurquoise3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleTurquoise4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleVioletRed;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleVioletRed1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleVioletRed2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleVioletRed3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PaleVioletRed4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PapayaWhip;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PeachPuff;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PeachPuff2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PeachPuff3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PeachPuff4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:peru;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Pink;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:pink2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:pink3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:pink4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Plum;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:plum1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:plum2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:plum3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:plum4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:PowderBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:purple;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:purple1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:purple2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:purple3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:purple4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Red;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:red1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:red2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:RosyBrown;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:RosyBrown1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:RosyBrown2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:RosyBrown3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:RosyBrown4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:RoyalBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:RoyalBlue1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:RoyalBlue2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:RoyalBlue3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:RoyalBlue4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:salmon1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:salmon2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:salmon3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:salmon4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SandyBrown;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SeaGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SeaGreen1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SeaGreen2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SeaGreen3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SeaGreen4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:seashell;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:seashell2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:seashell3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:seashell4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Sienna;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:sienna1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:sienna2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:sienna3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:sienna4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SkyBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SkyBlue1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SkyBlue2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SkyBlue3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SkyBlue4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SlateBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SlateBlue1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SlateBlue2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SlateBlue3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SlateBlue4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SlateGray;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SlateGray1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SlateGray2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SlateGray3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SlateGray4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:snow;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:snow2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:snow3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:snow4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SpringGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SpringGreen1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SpringGreen2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SpringGreen3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SpringGreen4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SteelBlue;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SteelBlue1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SteelBlue2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SteelBlue3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:SteelBlue4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Tan;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:tan1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:tan2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Thistle;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:thistle1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:thistle2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:thistle3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:thistle4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:tomato;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:tomato2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:tomato3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Turquoise;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:turquoise1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:turquoise2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:turquoise3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:turquoise4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Violet;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:VioletRed;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:VioletRed1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:VioletRed2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:VioletRed3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:VioletRed4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Wheat;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:wheat1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:wheat2;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:wheat3;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:wheat4;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Yellow;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:yellow1;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:YellowGreen;font-weight: bold;font-size:13px\">  " ,
    "<div style=\"color:Brown;font-weight: bold;font-size:13px\">  " ,*/




};
